// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzlpwqtnwnsewgikkbdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bHB3cXRud25zZXdnaWtrYmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyOTUxNjMsImV4cCI6MjA5NDg3MTE2M30.9tv6hwKS8j3ad5Wqx-SZJWeuHAEs2ZigQ-v46rAxtXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});